name: Send New Issue to Telegram Group
# Telegram Notify Action
# https://github.com/marketplace/actions/telegram-notify
# 
# Github Actions reference
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues
# https://developer.github.com/webhooks/event-payloads/#issues
# https://docs.github.com/en/rest/reference/issues#get-an-issue
# 
# To get TELEGRAM_TOKEN
# https://core.telegram.org/bots/api
# 
# To get TELEGRAM_TO
# https://api.telegram.org/bot<apiToken>/getUpdates
# Go for chat id

on:
  issues:
    types:
      - opened
jobs:
  send-to-group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          args: |
            <b>Título:</b> ${{ github.event.issue.title }}
            <b>Categoria:</b> ${{join(github.event.issue.labels.*.name, ', ')}}
            <b>Descrição:</b> ${{ github.event.issue.body }}
            <b>Link:</b> ${{ github.event.issue.html_url }}
